language: node_js
node_js:
  - "6.6.0"
before_install:
  - rvm install 2.2.5
install:
  - gem install jekyll
  - gem install percy-cli
  - npm install
before_script:
  - node_modules/gulp/bin/gulp.js build
script:
  - jekyll build
  - node_modules/gulp/bin/gulp.js test
  - percy snapshot --widths "375,1280" _jekyll/_site/ --baseurl "/vanilla-framework"
notifications:
  irc:
    channels:
      - "chat.freenode.net#vanilla-framework"
      - "chat.freenode.net#canonical-webteam"
    on_success: change
    on_failure: always
    on_success: change
  slack:
    rooms:
      - vanillaframework:wvRcrt4C6ODhvHxrUkTaKlD5#travis
