version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:1.6.8
      environment:
        SECRET_KEY: local_development_fake_key

jobs:
  percy:
    <<: *defaults
    steps:
      - checkout
      - run:
          # https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
          name: Install puppeteer dependencies
          command: |
            apt-get update
            apt-get -yq install gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt
      - run:
          name: Build the site resources
          command: yarn build
      - run:
          name: Run the site server
          command: ./entrypoint 0.0.0.0:${PORT}
          background: true
      - run:
          name: Wait for development server
          command: sleep 5
      - run:
          name: Check server status
          command: curl localhost:${PORT}/_status/check -I
      - run:
          name: Snapshot screenshots
          command: yarn percy

workflows:
  version: 2
  build:
    jobs:
      - percy
