name: Update Percy Baseline

on:
  push:
    branches:
      - main

jobs:
  snapshot:
    name: Take Percy snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - uses: ./.github/workflows/percy-snapshot
        with:
          branch_name: main
          commitsh: ${{ github.sha }}
          percy_token_write: ${{ secrets.PERCY_TOKEN_WRITE }}