# Mostly identical to https://github.com/canonical/webteam-devops/blob/285865893f8ace88e012a0f216f0b2827a18d488/.github/workflows/deploy.yaml
# This forked version will be used until This is the reason for https://github.com/canonical/webteam-devops/issues/4 is resolved.
name: Pack and Deploy

on:
  workflow_call:
    inputs:
      charm_name:
        required: true
        type: string
      channel:
        required: true
        type: string
      juju_controller_name:
        required: true
        type: string
      juju_model_name:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      VAULT_APPROLE_ROLE_ID:
        required: true
      VAULT_APPROLE_SECRET_ID:
        required: true
      CHARMHUB_TOKEN:
        required: true

jobs:
  setup:
    name: Check for charm changes
    runs-on: ubuntu-latest
    outputs:
      charm_changed: ${{ steps.check.outputs.charm_changed }}
    steps:
        # Make sure we have at least 2 commits to compare against
        # This is the only change from the original workflow as of https://github.com/canonical/webteam-devops/tree/285865893f8ace88e012a0f216f0b2827a18d488/.github/workflows
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # This is the reason for https://github.com/canonical/webteam-devops/issues/4
#      - name: Check for charm/ changes
#        id: check
#        run: |
#          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^charm/'; then
#            echo "charm_changed=true" >> "$GITHUB_OUTPUT"
#          else
#            echo "charm_changed=false" >> "$GITHUB_OUTPUT"
#          fi

  pack-rock:
    name: Pack Rock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup rockcraft
        run: sudo snap install rockcraft --classic

      - name: Pack rock
        run: rockcraft pack

      - name: Upload rock
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.charm_name }}-rock
          path: ./*.rock

  publish-image:
    name: Publish OCI Image
    runs-on: ubuntu-latest
    needs: [pack-rock]
    outputs:
      image_url: ${{ steps.set_image_url.outputs.image_url }}
    steps:
      - name: Get Rock
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.charm_name }}-rock

      - name: Set image URL
        id: set_image_url
        run: echo "image_url=ghcr.io/${GITHUB_REPOSITORY}:$(date +%s)-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Push to GHCR
        run: skopeo --insecure-policy copy oci-archive:$(ls *.rock) docker://${{ steps.set_image_url.outputs.image_url }} --dest-creds "canonical:${{ secrets.GITHUB_TOKEN }}"

      - name: Pull image into registry
        run: docker pull ${{ steps.set_image_url.outputs.image_url }}

      - name: Upload flask app OCI image
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: |
          sudo snap install charmcraft --classic
          charmcraft upload-resource ${{ inputs.charm_name }} flask-app-image --image=$(docker images --format "{{.ID}}" | head -n 1) --verbosity=trace

      - name: Attach resource to charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: |
          revision_number=$(charmcraft revisions "${{ inputs.charm_name }}" | awk 'NR==2 {print $1}')
          resource_revision_number=$(charmcraft resource-revisions "${{ inputs.charm_name }}" flask-app-image | awk 'NR==2 {print $1}')
          charmcraft release "${{ inputs.charm_name }}" --channel=${{ inputs.channel }} --revision $revision_number --resource flask-app-image:$resource_revision_number

  pack-charm:
    name: Pack Charm
    runs-on: ubuntu-latest
    needs: setup
    #  https://github.com/canonical/webteam-devops/issues/4
    # if: needs.setup.outputs.charm_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup charmcraft
        run: sudo snap install charmcraft --classic --channel=latest/stable

      - name: Fetch libs
        run: |
          cd ./charm
          charmcraft fetch-libs

      - name: Pack charm
        run: charmcraft pack -v --project-dir ./charm

      - name: Upload charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: charmcraft upload ./*.charm

      - name: Release charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: |
          revision_number=$(charmcraft revisions ${{ inputs.charm_name }} | awk 'NR==2 {print $1}')
          charmcraft release ${{ inputs.charm_name }} --channel=${{ inputs.channel }} --revision $revision_number

  deploy:
    name: Deploy to Environment
    if: always()
    needs: [setup, pack-rock, pack-charm, publish-image]
    uses: ./.github/workflows/webteam-devops-juju-deploy-fork.yaml
    with:
      charm_name: ${{ inputs.charm_name }}
      channel: ${{ inputs.channel }}
      juju_controller_name: ${{ inputs.juju_controller_name }}
      juju_model_name: ${{ inputs.juju_model_name }}
      environment: ${{ inputs.environment || '' }}
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}